#!/bin/bash
set -e
cd /workspace/agents/video-auto

# 配置 git 用户
git config user.name "video-auto-bot"
git config user.email "video-auto@agents.ai"

# 添加本次更新文件
git add OPTIMIZATION.md
git add AGENTS.md
git add ARCHITECTURE.md
git add video/complete_pipeline.py
git add video/2026-04-04/

# 如果有新增文件也添加
git add -f video/2026-04-04/combined/combined_video.mp4 2>/dev/null || true
git add -f video/2026-04-04/combined/cover.png 2>/dev/null || true

# Commit
git commit -m "🎬 video-auto 2026-04-04 更新：端到端流水线打通，10段视频拼接完成

- ✅ 端到端测试：2026年AI视频工具最新进展主题
- ✅ batch_image_to_video 生成10个视频片段
- ✅ 纯Python MP4拼接验证成功（9.7MB）
- ✅ TTS配音6段生成完成
- ✅ OPTIMIZATION.md / AGENTS.md 文档更新
- ⚠️ 音视频合并待自动化（ffmpeg缺失）

Generated by OpenClaw video-auto Agent"

# Push
git push origin master

echo "✅ GitHub 推送完成"
